spring:
  main:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/employee_management_system
      username: root
      password: Sandhani005@
  jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
server:
  port: 8133